name: 'Uppercase'
description: 'Convet text to uppercase'
author: 'LittleBear-6w6'

# Define your inputs here.
inputs:
  text:
    description: 'Text to be conveted to uppercase'
    required: true

# Define your outputs here.
outputs:
  uppercase-text:
    description: 'Text conveted to uppercase'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.text }}

branding:
  icon: 'chevrons-up'
  color: 'green'